server.port: 18080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:
#    schema: classpath:/sql/test/schema.sql
#    data: classpath:/sql/test/data.sql
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
#      hibernate: DEBUG
      springframework:
        web: DEBUG





