server.port: 18080

# SPRING
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  devtools:
    livereload:
      enabled: true

# LOGGING
logging:
  level:
#    root: debug
    com.yaboong: debug
    org.springframework.web: debug

# AWS
aws:
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  s3:
    region: ap-northeast-2
    bucket-name: yaboong-test-data
    end-point-url: https://s3.${aws.s3.region}.amazonaws.com





