INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #1' , 'content #1' , 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #2' , 'content #2' , 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #3' , 'content #3' , 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #4' , 'content #4' , 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #5' , 'content #5' , 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #6' , 'content #6' , 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #7' , 'content #7' , 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #8' , 'content #8' , 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #9' , 'content #9' , 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #10', 'content #10', 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #11', 'content #11', 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #12', 'content #12', 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #13', 'content #13', 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #14', 'content #14', 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #15', 'content #15', 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #16', 'content #16', 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #17', 'content #17', 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #18', 'content #18', 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #19', 'content #19', 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #20', 'content #20', 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #21', 'content #21', 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #22', 'content #22', 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #23', 'content #23', 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #24', 'content #24', 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #25', 'content #25', 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #26', 'content #26', 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #27', 'content #27', 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #28', 'content #28', 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #29', 'content #29', 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO post (category, title, content, view_count, like_count, `status`, created_by, modified_by) VALUES ('GENERAL', 'title #30', 'content #30', 0, 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (1, 'post #1 comment content #1', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (1, 'post #1 comment content #2', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (1, 'post #1 comment content #3', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (1, 'post #1 comment content #4', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (1, 'post #1 comment content #5', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (1, 'post #1 comment content #6', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (1, 'post #1 comment content #7', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (1, 'post #1 comment content #8', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (1, 'post #1 comment content #9', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (1, 'post #1 comment content #10', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (2, 'post #2 comment content #1', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (2, 'post #2 comment content #2', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (2, 'post #2 comment content #3', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (2, 'post #2 comment content #4', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (2, 'post #2 comment content #5', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (2, 'post #2 comment content #6', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (2, 'post #2 comment content #7', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (2, 'post #2 comment content #8', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (2, 'post #2 comment content #9', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (2, 'post #2 comment content #10', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (3, 'post #3 comment content #1', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (3, 'post #3 comment content #2', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (3, 'post #3 comment content #3', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (3, 'post #3 comment content #4', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (3, 'post #3 comment content #5', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (3, 'post #3 comment content #6', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (3, 'post #3 comment content #7', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (3, 'post #3 comment content #8', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (3, 'post #3 comment content #9', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (3, 'post #3 comment content #10', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (4, 'post #4 comment content #1', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (4, 'post #4 comment content #2', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (4, 'post #4 comment content #3', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (4, 'post #4 comment content #4', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (4, 'post #4 comment content #5', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (4, 'post #4 comment content #6', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (4, 'post #4 comment content #7', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (4, 'post #4 comment content #8', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (4, 'post #4 comment content #9', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (4, 'post #4 comment content #10', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (5, 'post #5 comment content #1', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (5, 'post #5 comment content #2', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (5, 'post #5 comment content #3', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (5, 'post #5 comment content #4', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (5, 'post #5 comment content #5', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (5, 'post #5 comment content #6', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (5, 'post #5 comment content #7', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (5, 'post #5 comment content #8', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (5, 'post #5 comment content #9', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (5, 'post #5 comment content #10', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (6, 'post #6 comment content #1', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (6, 'post #6 comment content #2', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (6, 'post #6 comment content #3', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (6, 'post #6 comment content #4', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (6, 'post #6 comment content #5', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (6, 'post #6 comment content #6', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (6, 'post #6 comment content #7', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (6, 'post #6 comment content #8', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (6, 'post #6 comment content #9', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (6, 'post #6 comment content #10', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (7, 'post #7 comment content #1', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (7, 'post #7 comment content #2', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (7, 'post #7 comment content #3', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (7, 'post #7 comment content #4', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (7, 'post #7 comment content #5', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (7, 'post #7 comment content #6', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (7, 'post #7 comment content #7', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (7, 'post #7 comment content #8', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (7, 'post #7 comment content #9', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (7, 'post #7 comment content #10', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (8, 'post #8 comment content #1', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (8, 'post #8 comment content #2', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (8, 'post #8 comment content #3', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (8, 'post #8 comment content #4', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (8, 'post #8 comment content #5', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (8, 'post #8 comment content #6', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (8, 'post #8 comment content #7', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (8, 'post #8 comment content #8', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (8, 'post #8 comment content #9', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (8, 'post #8 comment content #10', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (9, 'post #9 comment content #1', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (9, 'post #9 comment content #2', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (9, 'post #9 comment content #3', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (9, 'post #9 comment content #4', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (9, 'post #9 comment content #5', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (9, 'post #9 comment content #6', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (9, 'post #9 comment content #7', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (9, 'post #9 comment content #8', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (9, 'post #9 comment content #9', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (9, 'post #9 comment content #10', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (10, 'post #10 comment content #1', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (10, 'post #10 comment content #2', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (10, 'post #10 comment content #3', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (10, 'post #10 comment content #4', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (10, 'post #10 comment content #5', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (10, 'post #10 comment content #6', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (10, 'post #10 comment content #7', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (10, 'post #10 comment content #8', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (10, 'post #10 comment content #9', 0, 'NORMAL', 'admin', 'admin');
INSERT INTO `comment` (post_id, content, like_count, `status`, created_by, modified_by) VALUES (10, 'post #10 comment content #10', 0, 'NORMAL', 'admin', 'admin');
