= Post API Document
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4

[[resources-posts]]
== 게시물

[[resources-posts-get]]
=== 게시물 조회

`GET` 요청으로 게시물 하나를 조회할 수 있다.

operation::posts-get[snippets='curl-request,http-request,http-response,httpie-request,links,request-headers,request-body,response-headers,response-body,response-fields']


[[resources-query-posts]]
=== 게시물 목록 조회

`GET` 요청과 page, size 파라미터로 게시물 목록을 조회할 수 있다.
한번에 최대로 조회 가능한 size 는 10 이다.

operation::query-posts[snippets='curl-request,http-request,http-response,httpie-request,links,request-headers,request-body,response-headers,response-body,response-fields']


[[resources-create-post]]
=== 게시물 등록
`POST` 요청으로 새로운 게시물을 등록할 수 있다.

operation::create-post[snippets='curl-request,http-request,http-response,httpie-request,links,request-headers,request-body,response-headers,response-body,response-fields']


[[resources-update-post]]
=== 게시물 수정
`PUT` 요청으로 기존 게시물을 수정할 수 있다.

operation::update-post[snippets='curl-request,http-request,http-response,httpie-request,links,request-headers,request-body,response-headers,response-body,response-fields']


[[resources-delete-post]]
=== 게시물 삭제
`DELETE` 요청으로 기존 게시물을 삭제할 수 있다.
물리적으로 삭제하는 것이 아니라 status 컬럼을 DELETED 로 변경하는 논리삭제 작업이다.

operation::delete-post[snippets='curl-request,http-request,http-response,httpie-request,links,request-headers,request-body,response-headers,response-body,response-fields']


[[resources-errors]]
== 오류

[[errors-post]]
=== 게시물 생성/수정 오류

[[error-post-null-param]]
==== 필드가 null 인 경우
Request body 의 json 필드가 required 인데, null 값을 포함하는 경우 아래와 같은 오류를 반환한다.

operation::error-create-update-post-null-param[snippets='http-response,response-headers,response-body,response-fields']


[[error-post-invalid-param]]
==== 제약사항을 어긴 경우
Request body 의 json 필드가 유효하지 않은 값을 포함하는 경우 아래와 같은 오류를 반환한다.
`좋아요 개수는 조회수보다 많을 수 없다` 와 같은 제약을 만족하지 못한 경우이다.

operation::error-create-update-post-invalid-param[snippets='http-response,response-headers,response-body,response-fields']