### POST 등록
POST http://localhost:18080/posts
Content-Type: application/json

{
  "category": "GENERAL",
  "title": "TEST TITLE",
  "content": "TEST CONTENT",
  "likeCount": 0,
  "viewCount": 0
}

### POST 조회
GET http://localhost:18080/posts/1
Accept: application/json

### POST 수정
PUT http://localhost:18080/posts/1
Content-Type: application/json

{
  "category": "IT",
  "title": "UPDATED TITLE 2",
  "viewCount": 1,
  "likeCount": 0,
  "content": "UPDATED CONTENT 2"
}

### POST 논리삭제
DELETE http://localhost:18080/posts/1
Content-Type: application/json

{
  "deletedYn": "Y"
}

### COMMENT 등록
POST http://localhost:18080/posts/1/comments
Content-Type: application/json

{
  "postId": 1,
  "content": "comment for post #1",
  "likeCount": 0
}

### COMMENT 수정
PUT http://localhost:18080/posts/1/comments/1
Content-Type: application/json

{
  "content": "comment for post #1 modified 1st",
  "likeCount": 100
}

### COMMENT 논리삭제
DELETE http://localhost:18080/posts/1/comments/1
Content-Type: application/json

###

